"""QuantForge: fast, dependency-free options pricing and risk engine.

Closed-form Black-Scholes-Merton pricing, full analytic Greeks, robust
implied-volatility solving, and a binomial lattice for American exercise.

Everything is pure Python (standard library only) so it drops into any
runtime with no compiled dependencies.
"""

from .bsm import (
    OptionType,
    price,
    call_price,
    put_price,
    forward_price,
    put_call_parity_residual,
    implied_forward as implied_forward_from_parity,
    implied_discount_factor,
    box_spread_implied_rate,
    rho_discount,
    delta,
    gamma,
    vega,
    theta,
    rho,
    epsilon,
    greeks,
    Greeks,
)
from .implied import implied_volatility, implied_vol_smile
from .binomial import american_price
from .leisen_reimer import (
    leisen_reimer_price, leisen_reimer_greeks, leisen_reimer_american_accel,
)
from .trinomial import trinomial_price, richardson_american
from .lsm import (
    bermudan_lsm, bermudan_lsm_local_vol, bermudan_lsm_greeks,
    bermudan_max_call_lsm, bermudan_max_call_lsm_greeks, bermudan_spread_lsm,
    bermudan_spread_lsm_greeks, bermudan_min_put_lsm,
    bermudan_min_put_lsm_greeks, bermudan_basket_lsm,
    bermudan_basket_lsm_greeks,
)
from .mlmc import mlmc_asian
from .perpetual import perpetual_american, perpetual_exercise_boundary
from .forward import implied_forward, ForwardResult, dividend_curve
from .forwardstart import (
    forward_start_price, forward_start_greeks, cliquet_price, cliquet_greeks,
)
from .chooser import (
    chooser_option, chooser_option_greeks,
    complex_chooser_option, complex_chooser_option_greeks,
)
from .compound import compound_option, compound_option_greeks
from .extendible import (
    holder_extendible_call, holder_extendible_call_greeks,
    holder_extendible_put, holder_extendible_put_greeks,
    writer_extendible_put, writer_extendible_put_greeks,
    writer_extendible_call, writer_extendible_call_greeks,
)
from .quanto import (
    quanto_option, compo_option, quanto_option_greeks, compo_option_greeks,
)
from .displaced import (
    displaced_diffusion_price, displaced_diffusion_greeks, displaced_implied_shift,
    displaced_diffusion_smile,
)
from .hedging import StickyRule, smile_delta, smile_delta_from_smile, skew_slope
from .lookback import (
    floating_strike_lookback, fixed_strike_lookback, lookback_greeks,
    discrete_fixed_strike_lookback, discrete_fixed_strike_lookback_greeks,
)
from .heston import heston_price, heston_smile
from .heston_mc import (
    heston_qe_mc, heston_cv_mc, heston_pathwise_delta, heston_mc_greeks,
)
from .bates import bates_price, bates_greeks, bates_smile
from .double_heston import (
    double_heston_price, double_heston_greeks, double_heston_smile,
)
from .rough_heston import (
    rough_heston_price, rough_heston_greeks, rough_heston_smile,
)
from .double_heston_calib import calibrate_double_heston
from .heston_calib import calibrate_heston
from .lsv import calibrate_leverage as calibrate_lsv_leverage
from .pde import (
    crank_nicolson_price, crank_nicolson_greeks, crank_nicolson_barrier,
    crank_nicolson_digital, crank_nicolson_no_touch,
)
from .pde2d import (
    adi_two_asset, adi_spread_option, adi_two_asset_cs, adi_two_asset_american,
)
from .pde_asian import asian_pde_price
from .kou import kou_price, kou_greeks, kou_smile
from .cgmy import cgmy_price, cgmy_greeks, cgmy_smile
from .nig import nig_price, nig_greeks, nig_smile
from .meixner import meixner_price, meixner_greeks, meixner_smile
from .levycalib import calibrate_levy_smile, levy_psi
from .levysurface import LevySurface, LevyCalendarViolation
from .carrmadan import (
    levy_price, carr_madan_strip, carr_madan_smile_strip, cos_price, cos_greeks,
)
from .rbergomi import (
    rbergomi_price, rbergomi_smile, rbergomi_price_cv, rbergomi_smile_cv,
    rbergomi_greeks_cv,
)
from .bachelier import (
    bachelier_price, bachelier_delta, bachelier_gamma, bachelier_vega,
    bachelier_implied_vol, bachelier_greeks, bachelier_theta,
    bachelier_cash_or_nothing, bachelier_asset_or_nothing,
)
from .variancegamma import (
    variance_gamma_price, variance_gamma_greeks, variance_gamma_smile,
)
from .hedgesim import simulate_delta_hedge, HedgeResult
from .merton import merton_jump_price, merton_jump_greeks, merton_smile
from .density import (
    risk_neutral_density, risk_neutral_cdf, price_from_density, density_total_mass,
)
from .varswap import (
    variance_swap_strike, volatility_swap_strike, variance_swap_from_smile,
    volatility_swap_bounds_from_smile,
    corridor_variance_swap_from_smile, gamma_swap_from_smile,
    forward_variance_swap_from_smile, variance_term_structure,
)
from .vix import (
    vix_from_chain, vix_from_smile, svix_from_smile, equity_premium_lower_bound,
)
from .bkm import bkm_moments_from_smile, skew_swap_from_smile
from .vrp import realized_variance, variance_risk_premium
from .mc_greeks import (
    lr_greeks, pathwise_delta, lr_digital_delta, asian_pathwise_vega,
    mixed_gamma, smoothed_digital_delta, barrier_lr_delta, lr_digital_greeks,
)
from .moment_premium import moment_risk_premia
from .rnd import (
    risk_neutral_density_from_smile, density_grid_from_smile,
    price_payoff_from_density, risk_neutral_cdf_from_smile,
    risk_neutral_quantile_from_smile, risk_neutral_var_from_smile,
    risk_neutral_cvar_from_smile, smile_arbitrage_violations,
    smile_is_arbitrage_free, calendar_arbitrage_violations,
    surface_is_calendar_arbitrage_free, surface_arbitrage_report,
    surface_is_arbitrage_free,
)
from .density_metrics import (
    tail_probability, density_entropy, expected_shortfall,
    kl_divergence_smiles, wasserstein_smiles,
)
from .density_var import density_var_es
from .multiasset import (
    exchange_option, spread_option, spread_option_bs, basket_option,
    geometric_basket_option, geometric_basket_greeks,
    best_of_call, worst_of_call,
    best_of_call_closed, worst_of_call_closed,
    best_of_put_closed, worst_of_put_closed, two_asset_digital,
    two_asset_asset_or_nothing, correlation_option, two_asset_gap_option,
    two_asset_digital_greeks,
    exchange_greeks, spread_greeks, spread_option_bs_greeks, basket_greeks,
    rainbow_greeks,
    implied_spread_correlation, implied_spread_correlation_bs,
    implied_geometric_basket_correlation, implied_exchange_correlation,
)
from .strategy import (
    payoff_at_expiry, payoff_profile, break_evens,
    vertical_spread, straddle, strangle, risk_reversal, butterfly, iron_condor,
    ratio_spread, backspread, calendar_spread, diagonal_spread,
    box_spread, synthetic_forward, collar, strategy_report,
)
from .localvol import dupire_local_vol, local_vol_from_implied, sabr_local_vol
from .spline import CubicSpline, SmileSpline
from .rates import (
    CapletPeriod, caplet_price, cap_price, floor_price, collar_price,
    caplet_floorlet_parity, annuity, swaption_price, swaption_parity,
    compounded_overnight_rate, simple_average_rate,
    compounded_rate_with_lookback, compounded_rate_with_lockout,
    caplet_greeks, cap_greeks, floor_greeks, swaption_greeks,
    black_swaption_price, black_swaption_greeks,
    swaption_implied_normal_vol, swaption_implied_black_vol,
    sabr_swaption_price, sabr_cap_price, sabr_floor_price,
    caplet_implied_normal_vol,
)
from .vasicek import (
    zero_coupon_bond, zero_coupon_yield, bond_option,
    bond_option_greeks as vasicek_bond_option_greeks,
    bond_greeks as vasicek_bond_greeks,
    coupon_bond_option as vasicek_coupon_bond_option,
    swaption as vasicek_swaption,
    caplet as vasicek_caplet, floorlet as vasicek_floorlet,
    cap as vasicek_cap, floor as vasicek_floor,
    expected_rate as vasicek_expected_rate,
    rate_variance as vasicek_rate_variance,
    stationary_distribution as vasicek_stationary_distribution,
)
from .cir import (
    cir_zero_coupon_bond, cir_zero_coupon_yield, cir_bond_greeks,
    cir_bond_option, cir_coupon_bond_option, cir_swaption,
    cir_caplet, cir_floorlet, cir_cap, cir_floor,
    cir_expected_rate, cir_rate_variance, cir_stationary_distribution,
)
from .holee import (
    holee_zero_coupon_bond, holee_zero_coupon_yield, holee_bond_greeks,
    holee_bond_option, holee_coupon_bond_option, holee_swaption,
    holee_caplet, holee_floorlet, holee_cap, holee_floor,
    holee_expected_rate, holee_rate_variance,
)
from .inflation import (
    index_ratio, inflation_adjusted_principal, fisher_real_rate,
    fisher_nominal_rate, breakeven_inflation, real_from_breakeven,
    linker_price, linker_real_yield,
    linker_real_duration, linker_real_convexity, linker_real_dv01,
    deflation_floored_redemption, deflation_floor_value, yoy_inflation_rate,
    zc_inflation_swap_rate, zc_inflation_swap_value,
    inflation_curve_from_zc_swaps, forward_inflation_rate, yoy_swap_value,
    reference_cpi, index_ratio_interpolated,
    normalize_seasonal_factors, apply_seasonality, deseasonalize,
    yoy_caplet_price, yoy_cap_price, yoy_cap_implied_vol,
    yoy_caplet_price_normal, yoy_caplet_implied_normal_vol,
    real_zero_curve, nominal_zero_curve, real_discount_factor,
)
from .copula import (
    gaussian_copula, clayton_copula, gumbel_copula,
    clayton_lower_tail_dependence, gumbel_upper_tail_dependence,
    clayton_theta_from_tau, gumbel_theta_from_tau,
    frank_copula, gaussian_copula_joint_default, first_to_default_probability,
    vasicek_loss_cdf, vasicek_loss_quantile, cdo_tranche_expected_loss,
    cdo_tranche_expected_loss_mc,
)
from .futures_convexity import (
    ho_lee_convexity_adjustment, hull_white_convexity_adjustment,
    forward_from_futures, futures_from_forward,
    forward_curve_from_futures_strip, stub_discount_factors_from_forwards,
)
from .equity_swap import (
    total_return_leg, financing_leg, total_return_swap_value, trs_fair_spread,
    dividend_swap_fair_strike, dividend_swap_value,
    variance_swap_payoff, vega_notional_to_variance_notional,
    volatility_swap_payoff, variance_swap_mtm,
)
from .actuarial import (
    survival_probabilities, life_annuity_due, term_insurance,
    whole_life_insurance, pure_endowment, endowment_insurance,
    temporary_life_annuity_due, net_level_premium,
    gompertz_makeham_hazard, gompertz_makeham_survival,
    gompertz_makeham_survival_curve, curtate_life_expectancy,
    cat_layer_loss, cat_expected_loss, cat_bond_spread, cat_bond_price,
)
from .structured import (
    note_zero_coupon_bond, principal_protected_note, reverse_convertible,
    note_embedded_option_value, capped_principal_protected_note,
    reverse_convertible_fair_coupon, buffered_note,
)
from .execution import (
    execution_trajectory, execution_trades, expected_cost, cost_variance,
    efficient_frontier_point,
    kyle_lambda, kyle_impact, square_root_impact, implementation_shortfall,
    twap_schedule, vwap_schedule, pov_schedule,
)
from .equity_comp import (
    dilution_factor, warrant_price, eso_expected_life, eso_value,
    pv_dividends, discrete_dividend_price, forward_with_dividends,
    conversion_value, straight_bond_floor, convertible_bond_value,
    conversion_premium, investment_premium, convertible_breakeven_years,
)
from .mbs import (
    monthly_payment, cpr_to_smm, smm_to_cpr, psa_cpr, amortization_schedule,
    mbs_cashflows, weighted_average_life,
    mbs_cashflows_psa, mbs_price, mbs_yield,
    mbs_price_with_spread, mbs_zspread, mbs_effective_duration,
    mbs_effective_convexity, sequential_cmo, tranche_wal,
    pac_schedule, pac_support_split,
)
from .weather import (
    heating_degree_days, cooling_degree_days, degree_day_index,
    degree_day_swap_payoff, degree_day_option,
    degree_day_swap_rate, degree_day_collar, degree_day_option_mc,
    seasonal_mean_temperature, expected_temperature, temperature_variance,
)
from .xva import (
    marginal_default_probs, cva, dva, bcva,
    swap_expected_exposure, fva,
    swap_potential_future_exposure, wrong_way_cva,
    collateralized_exposure, collateralized_exposure_profile,
    mva, swap_cva,
)
from .commodity import (
    commodity_forward, implied_convenience_yield, implied_storage_cost,
    net_cost_of_carry, commodity_forward_curve, is_backwardation,
    commodity_calendar_spread, convenience_yield_curve, seasonal_forward,
    schwartz_log_mean, schwartz_log_variance, schwartz_forward,
    schwartz_option, mean_reversion_half_life, schwartz_implied_alpha,
    roll_yield, carry_roll_yield, schwartz_futures_volatility,
    schwartz_smith_log_mean, schwartz_smith_log_variance, schwartz_smith_forward,
    schwartz_smith_futures_volatility,
    margrabe_exchange_option, kirk_spread_option,
    bachelier_spread_option, spread_option_mc, spark_spread_option, tolling_value,
    commodity_swap_rate, commodity_swap_value, asian_commodity_option,
    geometric_asian_option, asian_commodity_option_mc, turnbull_wakeman_asian,
)
from .bondmath import (
    bond_cashflows, dated_bond_cashflows, dated_bond_price, dated_bond_yield,
    dated_accrued_interest, dated_clean_price,
    bond_price_from_yield, macaulay_duration,
    modified_duration, convexity, dv01 as bond_dv01, yield_to_maturity,
    price_from_curve, key_rate_durations, effective_duration_from_curve,
    accrued_interest, dirty_price, clean_price,
)
from .credit import (
    SurvivalCurve, risky_annuity, cds_protection_leg, cds_premium_leg,
    cds_par_spread, cds_value, cds_greeks, bootstrap_survival_curve,
    risky_bond_price, risky_bond_yield_spread, cds_accrual_on_default,
)
from .overhedge import (
    Overhedge, digital_call_overhedge, digital_put_overhedge, overhedge_payoff,
)
from .dv01 import KeyRateDV01, key_rate_dv01
from .bookgreeks import (
    BookSecondOrder, book_second_order, ThetaCarry, theta_carry_report,
    BumpGreeks, book_bump_greeks,
)
from .attribution import PnLAttribution, attribute_pnl, CarryRoll, carry_roll_pnl
from .income import IncomeMetrics, covered_call, cash_secured_put
from .vegabucket import VegaBuckets, vega_buckets
from .qmc import halton, european_qmc
from .sobol import (
    Sobol, brownian_bridge_path, sobol_european, sobol_european_rqmc, sobol_asian,
    sobol_asian_rqmc, sobol_lookback_rqmc, sobol_fixed_lookback_rqmc,
    sobol_barrier_rqmc, sobol_barrier_digital_rqmc, sobol_autocallable_rqmc,
    sobol_double_knockout_rqmc, sobol_cliquet_rqmc, sobol_average_strike_rqmc,
    sobol_geometric_asian_rqmc, sobol_parisian_rqmc,
    sobol_arithmetic_asian_rqmc,
)
from .correlation import (
    implied_correlation, index_vol_from_correlation, dispersion_basket_vol,
    correlation_term_structure, dispersion_trade_pnl,
    ewma_covariance, ewma_correlation, realized_beta,
)
from .perfmetrics import (
    sharpe_ratio, sortino_ratio, max_drawdown, calmar_ratio, hit_rate,
    profit_factor, drawdown_curve, longest_drawdown_duration, rolling_sharpe,
    omega_ratio, tail_ratio, tracking_error, information_ratio,
    up_capture, down_capture, downside_beta,
    sample_skewness, sample_kurtosis, jarque_bera, cornish_fisher_var,
    historical_var as historical_var_series, historical_cvar,
    cumulative_return, annualized_return, annualized_volatility,
)
from .cev import cev_price, cev_greeks, cev_smile, noncentral_chisq_cdf
from .portopt import (
    min_variance_weights, max_sharpe_weights, risk_parity_weights,
    portfolio_variance, portfolio_return,
    target_return_weights, efficient_frontier,
    max_diversification_weights, diversification_ratio,
    portfolio_var, portfolio_cvar, component_var, marginal_var, var_budget,
    implied_equilibrium_returns, black_litterman_returns,
    black_litterman_weights,
)
from .sizing import (
    delta_hedge_shares, neutralize, vega_neutral_quantity, gamma_neutral_quantity,
    kelly_fraction_binary, kelly_fraction_continuous, kelly_growth_rate,
)
from .gramcharlier import (
    corrado_su_call, corrado_su_price, realized_skewness, realized_excess_kurtosis,
    calibrate_corrado_su, corrado_su_implied_vol, corrado_su_smile,
)
from .portfolio import Contract, Position, BookRisk, Book, price_book
from .svi import (
    SVIParams, calibrate_svi, svi_g, svi_butterfly_arbitrage, svi_is_butterfly_free,
    lee_wing_slopes, lee_bounds_ok, svi_repair_butterfly,
    svi_local_variance, svi_surface_local_vol, calibrate_svi_from_prices,
    svi_variance_swap_strike, svi_vix, svi_svix, svi_bkm_moments, svi_density,
)
from .ssvi import (
    SSVIParams, ssvi_phi, ssvi_total_variance, calibrate_ssvi,
    ssvi_butterfly_free, ssvi_calendar_free, ssvi_is_arbitrage_free,
    ssvi_local_variance, ssvi_local_vol_from_params,
    ssvi_local_vol_fn, ssvi_reprice_mc, calibrate_ssvi_arbitrage_free,
    ssvi_variance_swap_strike, ssvi_vix, ssvi_svix, ssvi_density,
    ssvi_bkm_moments,
)
from .sabr import (
    SABRParams, sabr_vol, sabr_normal_vol, calibrate_sabr, calibrate_sabr_lm,
    sabr_sensitivities, sabr_jacobian, sabr_option_greeks,
    sabr_variance_swap_strike, sabr_vix, sabr_bkm_moments,
    sabr_density, sabr_butterfly_arbitrage, sabr_is_arbitrage_free,
    sabr_repair_butterfly,
)
from .vannavolga import VannaVolgaSmile, pillar_vols
from .fxdelta import (
    atm_dns_strike, strike_from_delta, delta_from_strike, rr_bf_to_pillars,
)
from .fxforward import (
    fx_forward, forward_points, fx_swap_points, implied_base_rate,
    implied_price_rate, fx_forward_from_curves,
)
from .daycount import year_fraction, day_count
from .schedule import generate_schedule, adjust_business_day
from .volcube import VolCube
from .cms import (
    cms_adjustment_standard, cms_rate_convexity_replication, cms_rate,
    cms_adjustment_greeks,
)
from .surface import VolSurface, SurfaceSlice, CalendarViolation
from .exotics import (
    cash_or_nothing, asset_or_nothing, digital_greeks, barrier_option, barrier_greeks,
    discrete_barrier_option, partial_time_end_barrier_call,
    partial_time_start_barrier_call,
    range_binary, supershare, range_binary_greeks, supershare_greeks,
    geometric_asian, geometric_asian_greeks, arithmetic_asian, asian_greeks,
    discrete_geometric_asian, discrete_geometric_asian_greeks,
    discrete_arithmetic_asian, discrete_arithmetic_asian_greeks,
    seasoned_geometric_asian, seasoned_arithmetic_asian,
    seasoned_geometric_asian_greeks, seasoned_arithmetic_asian_greeks,
    average_strike_geometric_asian, average_strike_geometric_asian_greeks,
    average_strike_arithmetic_asian, average_strike_arithmetic_asian_greeks,
    one_touch, no_touch, double_no_touch, double_one_touch,
    double_no_touch_greeks, double_knock_out_call, double_knock_in_call,
    double_knock_out_call_greeks, double_knock_in_call_greeks,
    gap_option, gap_option_greeks, power_option, power_option_greeks,
    powered_option, powered_option_greeks,
    barrier_rebate, Barrier,
)
from .montecarlo import (
    MCResult, european_mc, european_cv_mc, european_is_mc,
    european_is_adaptive_mc, european_stratified_mc, spread_option_lhs_mc,
    basket_option_lhs_mc, replicated_mc, digital_is_mc, arithmetic_asian_mc,
    capped_cliquet_mc,
    barrier_mc, barrier_digital_mc, parisian_barrier_mc, local_vol_mc,
    average_strike_asian_mc, autocallable_mc, double_knockout_mc,
)
from .risk import VaRResult, parametric_var, historical_var, montecarlo_var
from .volatility import (
    close_to_close, ewma_vol, parkinson, garman_klass, rogers_satchell,
    yang_zhang, vol_report, VolReport, vol_cone, VolConePoint,
    fit_garch, garch_forecast, garch_term_variance, garch_option_price,
    GarchParams,
)
from .greeks2 import (
    vanna, vomma, volga, charm, veta, speed, zomma, color, ultima,
    dual_delta, dual_gamma,
)
from .scenario import ScenarioGrid, stress_grid, spot_ladder
from .american import (
    bjerksund_stensland, bjerksund_stensland_greeks, early_exercise_premium,
    bjerksund_stensland_1993, bjerksund_stensland_boundary,
)
from .kim import (
    kim_american_put, kim_american_call, kim_exercise_boundary, kim_put_greeks,
)
from .baw import baw_american, baw_critical_spot, baw_american_greeks
from .andreasenhuge import (
    andreasen_huge_prices, andreasen_huge_smile, andreasen_huge_calibrate,
    andreasen_huge_strike_greeks,
)
from .cheyette import (
    cheyette_G, cheyette_y, zero_bond as cheyette_zero_bond,
    bond_option as cheyette_bond_option, caplet as cheyette_caplet,
    bond_option_greeks as cheyette_bond_option_greeks,
    floorlet as cheyette_floorlet, cap as cheyette_cap, floor as cheyette_floor,
)
from .g2pp import (
    g2pp_V, zero_bond as g2pp_zero_bond, bond_option as g2pp_bond_option,
    caplet as g2pp_caplet, bond_option_greeks as g2pp_bond_option_greeks,
    floorlet as g2pp_floorlet, cap as g2pp_cap, floor as g2pp_floor,
)
from .bermudan_swaption import (
    bermudan_swaption_g2pp, bermudan_swaption_g2pp_greeks,
)
from .discount_curve import DiscountCurve, bootstrap_from_swaps
from .dualcurve import (
    forward_rate as dual_forward_rate, par_swap_rate as dual_par_swap_rate,
    swap_value as dual_swap_value, float_leg_value as dual_float_leg_value,
    calibrate_basis as dual_calibrate_basis, swap_dv01 as dual_swap_dv01,
)

# Vectorized NumPy fast path is optional; only expose it if NumPy is present.
try:  # pragma: no cover - trivial availability branch
    from .vectorized import (
        price_array, delta_array, gamma_array, vega_array, greeks_array,
        HAS_NUMPY,
    )
except ImportError:  # pragma: no cover
    HAS_NUMPY = False

__version__ = "1.437.0"

__all__ = [
    "OptionType",
    "price",
    "call_price",
    "put_price",
    "forward_price",
    "put_call_parity_residual",
    "implied_forward_from_parity",
    "implied_discount_factor",
    "box_spread_implied_rate",
    "rho_discount",
    "delta",
    "gamma",
    "vega",
    "theta",
    "rho",
    "epsilon",
    "greeks",
    "Greeks",
    "implied_volatility",
    "implied_vol_smile",
    "american_price",
    "leisen_reimer_price",
    "leisen_reimer_greeks",
    "leisen_reimer_american_accel",
    "trinomial_price",
    "richardson_american",
    "bermudan_lsm",
    "bermudan_lsm_local_vol",
    "bermudan_lsm_greeks",
    "bermudan_max_call_lsm",
    "bermudan_max_call_lsm_greeks",
    "bermudan_spread_lsm",
    "bermudan_spread_lsm_greeks",
    "bermudan_min_put_lsm",
    "bermudan_min_put_lsm_greeks",
    "bermudan_basket_lsm",
    "bermudan_basket_lsm_greeks",
    "mlmc_asian",
    "perpetual_american",
    "perpetual_exercise_boundary",
    "implied_forward",
    "ForwardResult",
    "dividend_curve",
    "forward_start_price",
    "forward_start_greeks",
    "cliquet_price",
    "cliquet_greeks",
    "chooser_option",
    "chooser_option_greeks",
    "complex_chooser_option",
    "complex_chooser_option_greeks",
    "compound_option",
    "compound_option_greeks",
    "holder_extendible_call",
    "holder_extendible_call_greeks",
    "holder_extendible_put",
    "holder_extendible_put_greeks",
    "writer_extendible_put",
    "writer_extendible_put_greeks",
    "writer_extendible_call",
    "writer_extendible_call_greeks",
    "quanto_option",
    "compo_option",
    "quanto_option_greeks",
    "compo_option_greeks",
    "displaced_diffusion_price",
    "displaced_diffusion_greeks",
    "displaced_implied_shift",
    "displaced_diffusion_smile",
    "StickyRule",
    "smile_delta",
    "smile_delta_from_smile",
    "skew_slope",
    "floating_strike_lookback",
    "fixed_strike_lookback",
    "lookback_greeks",
    "discrete_fixed_strike_lookback",
    "discrete_fixed_strike_lookback_greeks",
    "heston_price",
    "heston_smile",
    "heston_qe_mc",
    "heston_cv_mc",
    "heston_pathwise_delta",
    "heston_mc_greeks",
    "bates_price",
    "bates_greeks",
    "bates_smile",
    "double_heston_price",
    "double_heston_greeks",
    "double_heston_smile",
    "rough_heston_price",
    "rough_heston_greeks",
    "rough_heston_smile",
    "calibrate_double_heston",
    "calibrate_heston",
    "calibrate_lsv_leverage",
    "crank_nicolson_price",
    "crank_nicolson_greeks",
    "crank_nicolson_barrier",
    "crank_nicolson_digital",
    "crank_nicolson_no_touch",
    "adi_two_asset",
    "adi_spread_option",
    "adi_two_asset_cs",
    "adi_two_asset_american",
    "asian_pde_price",
    "kou_price",
    "kou_greeks",
    "kou_smile",
    "cgmy_price",
    "cgmy_greeks",
    "cgmy_smile",
    "nig_price",
    "nig_greeks",
    "nig_smile",
    "meixner_price",
    "meixner_greeks",
    "meixner_smile",
    "calibrate_levy_smile",
    "levy_psi",
    "LevySurface",
    "LevyCalendarViolation",
    "levy_price",
    "carr_madan_strip",
    "carr_madan_smile_strip",
    "cos_price",
    "cos_greeks",
    "rbergomi_price",
    "rbergomi_smile",
    "rbergomi_price_cv",
    "rbergomi_smile_cv",
    "rbergomi_greeks_cv",
    "bachelier_price",
    "bachelier_delta",
    "bachelier_gamma",
    "bachelier_vega",
    "bachelier_implied_vol",
    "bachelier_greeks",
    "bachelier_theta",
    "bachelier_cash_or_nothing",
    "bachelier_asset_or_nothing",
    "variance_gamma_price",
    "variance_gamma_greeks",
    "variance_gamma_smile",
    "simulate_delta_hedge",
    "HedgeResult",
    "merton_jump_price",
    "merton_jump_greeks",
    "merton_smile",
    "risk_neutral_density",
    "risk_neutral_cdf",
    "price_from_density",
    "density_total_mass",
    "variance_swap_strike",
    "volatility_swap_strike",
    "variance_swap_from_smile",
    "volatility_swap_bounds_from_smile",
    "corridor_variance_swap_from_smile",
    "gamma_swap_from_smile",
    "forward_variance_swap_from_smile",
    "variance_term_structure",
    "vix_from_chain",
    "vix_from_smile",
    "svix_from_smile",
    "equity_premium_lower_bound",
    "bkm_moments_from_smile",
    "skew_swap_from_smile",
    "realized_variance",
    "variance_risk_premium",
    "lr_greeks",
    "pathwise_delta",
    "lr_digital_delta",
    "asian_pathwise_vega",
    "mixed_gamma",
    "smoothed_digital_delta",
    "barrier_lr_delta",
    "lr_digital_greeks",
    "moment_risk_premia",
    "risk_neutral_density_from_smile",
    "density_grid_from_smile",
    "price_payoff_from_density",
    "risk_neutral_cdf_from_smile",
    "smile_arbitrage_violations",
    "smile_is_arbitrage_free",
    "calendar_arbitrage_violations",
    "surface_is_calendar_arbitrage_free",
    "surface_arbitrage_report",
    "surface_is_arbitrage_free",
    "risk_neutral_quantile_from_smile",
    "risk_neutral_var_from_smile",
    "risk_neutral_cvar_from_smile",
    "tail_probability",
    "density_entropy",
    "expected_shortfall",
    "kl_divergence_smiles",
    "wasserstein_smiles",
    "density_var_es",
    "exchange_option",
    "spread_option",
    "spread_option_bs",
    "basket_option",
    "geometric_basket_option",
    "geometric_basket_greeks",
    "best_of_call",
    "worst_of_call",
    "best_of_call_closed",
    "worst_of_call_closed",
    "best_of_put_closed",
    "worst_of_put_closed",
    "two_asset_digital",
    "two_asset_asset_or_nothing",
    "correlation_option",
    "two_asset_gap_option",
    "two_asset_digital_greeks",
    "exchange_greeks",
    "spread_greeks",
    "spread_option_bs_greeks",
    "basket_greeks",
    "rainbow_greeks",
    "implied_spread_correlation",
    "implied_exchange_correlation",
    "implied_spread_correlation_bs",
    "implied_geometric_basket_correlation",
    "payoff_at_expiry",
    "payoff_profile",
    "break_evens",
    "vertical_spread",
    "straddle",
    "strangle",
    "risk_reversal",
    "butterfly",
    "iron_condor",
    "ratio_spread",
    "backspread",
    "calendar_spread",
    "diagonal_spread",
    "box_spread",
    "synthetic_forward",
    "collar",
    "strategy_report",
    "dupire_local_vol",
    "local_vol_from_implied",
    "sabr_local_vol",
    "CubicSpline",
    "SmileSpline",
    "CapletPeriod",
    "caplet_price",
    "cap_price",
    "floor_price",
    "caplet_greeks",
    "cap_greeks",
    "floor_greeks",
    "collar_price",
    "caplet_floorlet_parity",
    "annuity",
    "swaption_price",
    "swaption_parity",
    "compounded_overnight_rate",
    "simple_average_rate",
    "compounded_rate_with_lookback",
    "compounded_rate_with_lockout",
    "swaption_greeks",
    "black_swaption_price",
    "black_swaption_greeks",
    "swaption_implied_normal_vol",
    "swaption_implied_black_vol",
    "sabr_swaption_price",
    "sabr_cap_price",
    "sabr_floor_price",
    "caplet_implied_normal_vol",
    "zero_coupon_bond",
    "zero_coupon_yield",
    "bond_option",
    "vasicek_bond_option_greeks",
    "vasicek_bond_greeks",
    "vasicek_coupon_bond_option",
    "vasicek_swaption",
    "vasicek_caplet",
    "vasicek_floorlet",
    "vasicek_cap",
    "vasicek_floor",
    "vasicek_expected_rate",
    "vasicek_rate_variance",
    "vasicek_stationary_distribution",
    "cir_zero_coupon_bond",
    "cir_zero_coupon_yield",
    "cir_bond_greeks",
    "cir_bond_option",
    "cir_coupon_bond_option",
    "cir_swaption",
    "cir_caplet",
    "cir_floorlet",
    "cir_cap",
    "cir_floor",
    "cir_expected_rate",
    "cir_rate_variance",
    "cir_stationary_distribution",
    "holee_zero_coupon_bond",
    "holee_zero_coupon_yield",
    "holee_bond_greeks",
    "holee_bond_option",
    "holee_coupon_bond_option",
    "holee_swaption",
    "holee_caplet",
    "holee_floorlet",
    "holee_cap",
    "holee_floor",
    "holee_expected_rate",
    "holee_rate_variance",
    "bond_cashflows",
    "dated_bond_cashflows",
    "dated_bond_price",
    "dated_bond_yield",
    "dated_accrued_interest",
    "dated_clean_price",
    "index_ratio",
    "inflation_adjusted_principal",
    "fisher_real_rate",
    "fisher_nominal_rate",
    "breakeven_inflation",
    "real_from_breakeven",
    "linker_price",
    "linker_real_yield",
    "linker_real_duration",
    "linker_real_convexity",
    "linker_real_dv01",
    "deflation_floored_redemption",
    "deflation_floor_value",
    "yoy_inflation_rate",
    "zc_inflation_swap_rate",
    "zc_inflation_swap_value",
    "inflation_curve_from_zc_swaps",
    "forward_inflation_rate",
    "yoy_swap_value",
    "reference_cpi",
    "index_ratio_interpolated",
    "normalize_seasonal_factors",
    "apply_seasonality",
    "deseasonalize",
    "yoy_caplet_price",
    "yoy_cap_price",
    "yoy_cap_implied_vol",
    "yoy_caplet_price_normal",
    "yoy_caplet_implied_normal_vol",
    "real_zero_curve",
    "nominal_zero_curve",
    "real_discount_factor",
    "gaussian_copula",
    "clayton_copula",
    "gumbel_copula",
    "clayton_lower_tail_dependence",
    "gumbel_upper_tail_dependence",
    "clayton_theta_from_tau",
    "gumbel_theta_from_tau",
    "frank_copula",
    "gaussian_copula_joint_default",
    "first_to_default_probability",
    "vasicek_loss_cdf",
    "vasicek_loss_quantile",
    "cdo_tranche_expected_loss",
    "cdo_tranche_expected_loss_mc",
    "ho_lee_convexity_adjustment",
    "hull_white_convexity_adjustment",
    "forward_from_futures",
    "futures_from_forward",
    "forward_curve_from_futures_strip",
    "stub_discount_factors_from_forwards",
    "total_return_leg",
    "financing_leg",
    "total_return_swap_value",
    "trs_fair_spread",
    "dividend_swap_fair_strike",
    "dividend_swap_value",
    "variance_swap_payoff",
    "vega_notional_to_variance_notional",
    "volatility_swap_payoff",
    "variance_swap_mtm",
    "survival_probabilities",
    "life_annuity_due",
    "term_insurance",
    "whole_life_insurance",
    "pure_endowment",
    "endowment_insurance",
    "temporary_life_annuity_due",
    "net_level_premium",
    "gompertz_makeham_hazard",
    "gompertz_makeham_survival",
    "gompertz_makeham_survival_curve",
    "curtate_life_expectancy",
    "cat_layer_loss",
    "cat_expected_loss",
    "cat_bond_spread",
    "cat_bond_price",
    "note_zero_coupon_bond",
    "principal_protected_note",
    "reverse_convertible",
    "note_embedded_option_value",
    "capped_principal_protected_note",
    "reverse_convertible_fair_coupon",
    "buffered_note",
    "execution_trajectory",
    "execution_trades",
    "expected_cost",
    "cost_variance",
    "efficient_frontier_point",
    "kyle_lambda",
    "kyle_impact",
    "square_root_impact",
    "implementation_shortfall",
    "twap_schedule",
    "vwap_schedule",
    "pov_schedule",
    "dilution_factor",
    "warrant_price",
    "eso_expected_life",
    "eso_value",
    "pv_dividends",
    "discrete_dividend_price",
    "forward_with_dividends",
    "conversion_value",
    "straight_bond_floor",
    "convertible_bond_value",
    "conversion_premium",
    "investment_premium",
    "convertible_breakeven_years",
    "monthly_payment",
    "cpr_to_smm",
    "smm_to_cpr",
    "psa_cpr",
    "amortization_schedule",
    "mbs_cashflows",
    "weighted_average_life",
    "mbs_cashflows_psa",
    "mbs_price",
    "mbs_yield",
    "mbs_price_with_spread",
    "mbs_zspread",
    "mbs_effective_duration",
    "mbs_effective_convexity",
    "sequential_cmo",
    "tranche_wal",
    "pac_schedule",
    "pac_support_split",
    "heating_degree_days",
    "cooling_degree_days",
    "degree_day_index",
    "degree_day_swap_payoff",
    "degree_day_option",
    "degree_day_swap_rate",
    "degree_day_collar",
    "degree_day_option_mc",
    "seasonal_mean_temperature",
    "expected_temperature",
    "temperature_variance",
    "marginal_default_probs",
    "cva",
    "dva",
    "bcva",
    "swap_expected_exposure",
    "fva",
    "swap_potential_future_exposure",
    "wrong_way_cva",
    "collateralized_exposure",
    "collateralized_exposure_profile",
    "mva",
    "swap_cva",
    "commodity_forward",
    "implied_convenience_yield",
    "implied_storage_cost",
    "net_cost_of_carry",
    "commodity_forward_curve",
    "is_backwardation",
    "commodity_calendar_spread",
    "convenience_yield_curve",
    "seasonal_forward",
    "schwartz_log_mean",
    "schwartz_log_variance",
    "schwartz_forward",
    "schwartz_option",
    "mean_reversion_half_life",
    "schwartz_implied_alpha",
    "roll_yield",
    "carry_roll_yield",
    "schwartz_futures_volatility",
    "schwartz_smith_log_mean",
    "schwartz_smith_log_variance",
    "schwartz_smith_forward",
    "schwartz_smith_futures_volatility",
    "margrabe_exchange_option",
    "kirk_spread_option",
    "bachelier_spread_option",
    "spread_option_mc",
    "spark_spread_option",
    "tolling_value",
    "commodity_swap_rate",
    "commodity_swap_value",
    "asian_commodity_option",
    "geometric_asian_option",
    "asian_commodity_option_mc",
    "turnbull_wakeman_asian",
    "bond_price_from_yield",
    "macaulay_duration",
    "modified_duration",
    "convexity",
    "bond_dv01",
    "yield_to_maturity",
    "price_from_curve",
    "key_rate_durations",
    "effective_duration_from_curve",
    "accrued_interest",
    "dirty_price",
    "clean_price",
    "SurvivalCurve",
    "risky_annuity",
    "cds_protection_leg",
    "cds_premium_leg",
    "cds_par_spread",
    "cds_value",
    "cds_greeks",
    "bootstrap_survival_curve",
    "risky_bond_price",
    "risky_bond_yield_spread",
    "cds_accrual_on_default",
    "Overhedge",
    "digital_call_overhedge",
    "digital_put_overhedge",
    "overhedge_payoff",
    "KeyRateDV01",
    "key_rate_dv01",
    "BookSecondOrder",
    "book_second_order",
    "ThetaCarry",
    "theta_carry_report",
    "BumpGreeks",
    "book_bump_greeks",
    "PnLAttribution",
    "attribute_pnl",
    "CarryRoll",
    "carry_roll_pnl",
    "IncomeMetrics",
    "covered_call",
    "cash_secured_put",
    "VegaBuckets",
    "vega_buckets",
    "halton",
    "european_qmc",
    "Sobol",
    "brownian_bridge_path",
    "sobol_european",
    "sobol_european_rqmc",
    "sobol_asian",
    "sobol_asian_rqmc",
    "sobol_lookback_rqmc",
    "sobol_fixed_lookback_rqmc",
    "sobol_barrier_rqmc",
    "sobol_barrier_digital_rqmc",
    "sobol_autocallable_rqmc",
    "sobol_double_knockout_rqmc",
    "sobol_cliquet_rqmc",
    "sobol_average_strike_rqmc",
    "sobol_geometric_asian_rqmc",
    "sobol_parisian_rqmc",
    "sobol_arithmetic_asian_rqmc",
    "implied_correlation",
    "index_vol_from_correlation",
    "dispersion_basket_vol",
    "dispersion_trade_pnl",
    "correlation_term_structure",
    "ewma_covariance",
    "ewma_correlation",
    "realized_beta",
    "sharpe_ratio",
    "sortino_ratio",
    "max_drawdown",
    "calmar_ratio",
    "hit_rate",
    "profit_factor",
    "drawdown_curve",
    "longest_drawdown_duration",
    "rolling_sharpe",
    "omega_ratio",
    "tail_ratio",
    "tracking_error",
    "information_ratio",
    "up_capture",
    "down_capture",
    "downside_beta",
    "sample_skewness",
    "sample_kurtosis",
    "jarque_bera",
    "cornish_fisher_var",
    "historical_var_series",
    "historical_cvar",
    "cumulative_return",
    "annualized_return",
    "annualized_volatility",
    "min_variance_weights",
    "max_sharpe_weights",
    "risk_parity_weights",
    "portfolio_variance",
    "portfolio_return",
    "target_return_weights",
    "efficient_frontier",
    "max_diversification_weights",
    "diversification_ratio",
    "portfolio_var",
    "portfolio_cvar",
    "component_var",
    "marginal_var",
    "var_budget",
    "implied_equilibrium_returns",
    "black_litterman_returns",
    "black_litterman_weights",
    "cev_price",
    "cev_greeks",
    "cev_smile",
    "noncentral_chisq_cdf",
    "delta_hedge_shares",
    "neutralize",
    "vega_neutral_quantity",
    "gamma_neutral_quantity",
    "kelly_fraction_binary",
    "kelly_fraction_continuous",
    "kelly_growth_rate",
    "corrado_su_call",
    "corrado_su_price",
    "calibrate_corrado_su",
    "corrado_su_implied_vol",
    "corrado_su_smile",
    "realized_skewness",
    "realized_excess_kurtosis",
    "Contract",
    "Position",
    "BookRisk",
    "Book",
    "price_book",
    "SVIParams",
    "calibrate_svi",
    "svi_g",
    "svi_butterfly_arbitrage",
    "svi_is_butterfly_free",
    "lee_wing_slopes",
    "lee_bounds_ok",
    "svi_repair_butterfly",
    "svi_local_variance",
    "svi_surface_local_vol",
    "calibrate_svi_from_prices",
    "svi_variance_swap_strike",
    "svi_vix",
    "svi_svix",
    "svi_bkm_moments",
    "svi_density",
    "SSVIParams",
    "ssvi_phi",
    "ssvi_total_variance",
    "calibrate_ssvi",
    "calibrate_ssvi_arbitrage_free",
    "ssvi_butterfly_free",
    "ssvi_calendar_free",
    "ssvi_is_arbitrage_free",
    "ssvi_local_variance",
    "ssvi_local_vol_from_params",
    "ssvi_local_vol_fn",
    "ssvi_reprice_mc",
    "ssvi_variance_swap_strike",
    "ssvi_vix",
    "ssvi_svix",
    "ssvi_density",
    "ssvi_bkm_moments",
    "SABRParams",
    "sabr_vol",
    "sabr_normal_vol",
    "calibrate_sabr",
    "calibrate_sabr_lm",
    "sabr_sensitivities",
    "sabr_jacobian",
    "sabr_option_greeks",
    "sabr_variance_swap_strike",
    "sabr_vix",
    "sabr_bkm_moments",
    "sabr_density",
    "sabr_butterfly_arbitrage",
    "sabr_is_arbitrage_free",
    "sabr_repair_butterfly",
    "VannaVolgaSmile",
    "pillar_vols",
    "atm_dns_strike",
    "strike_from_delta",
    "delta_from_strike",
    "rr_bf_to_pillars",
    "fx_forward",
    "forward_points",
    "fx_swap_points",
    "implied_base_rate",
    "implied_price_rate",
    "fx_forward_from_curves",
    "year_fraction",
    "day_count",
    "generate_schedule",
    "adjust_business_day",
    "VolCube",
    "cms_adjustment_standard",
    "cms_adjustment_greeks",
    "cms_rate_convexity_replication",
    "cms_rate",
    "VolSurface",
    "SurfaceSlice",
    "CalendarViolation",
    "cash_or_nothing",
    "asset_or_nothing",
    "range_binary",
    "supershare",
    "range_binary_greeks",
    "supershare_greeks",
    "digital_greeks",
    "barrier_option",
    "barrier_greeks",
    "discrete_barrier_option",
    "partial_time_end_barrier_call",
    "partial_time_start_barrier_call",
    "geometric_asian",
    "geometric_asian_greeks",
    "discrete_geometric_asian",
    "discrete_geometric_asian_greeks",
    "discrete_arithmetic_asian",
    "discrete_arithmetic_asian_greeks",
    "seasoned_geometric_asian",
    "seasoned_arithmetic_asian",
    "seasoned_geometric_asian_greeks",
    "seasoned_arithmetic_asian_greeks",
    "average_strike_geometric_asian",
    "average_strike_geometric_asian_greeks",
    "average_strike_arithmetic_asian",
    "average_strike_arithmetic_asian_greeks",
    "arithmetic_asian",
    "asian_greeks",
    "one_touch",
    "no_touch",
    "double_no_touch",
    "double_one_touch",
    "double_no_touch_greeks",
    "double_knock_out_call",
    "double_knock_in_call",
    "double_knock_out_call_greeks",
    "double_knock_in_call_greeks",
    "gap_option",
    "gap_option_greeks",
    "power_option",
    "power_option_greeks",
    "powered_option",
    "powered_option_greeks",
    "barrier_rebate",
    "Barrier",
    "MCResult",
    "european_mc",
    "european_cv_mc",
    "european_is_mc",
    "european_is_adaptive_mc",
    "european_stratified_mc",
    "spread_option_lhs_mc",
    "basket_option_lhs_mc",
    "replicated_mc",
    "digital_is_mc",
    "arithmetic_asian_mc",
    "capped_cliquet_mc",
    "barrier_mc",
    "barrier_digital_mc",
    "parisian_barrier_mc",
    "local_vol_mc",
    "average_strike_asian_mc",
    "autocallable_mc",
    "double_knockout_mc",
    "VaRResult",
    "parametric_var",
    "historical_var",
    "montecarlo_var",
    "close_to_close",
    "ewma_vol",
    "parkinson",
    "garman_klass",
    "rogers_satchell",
    "yang_zhang",
    "vol_report",
    "VolReport",
    "vol_cone",
    "VolConePoint",
    "fit_garch",
    "garch_forecast",
    "garch_term_variance",
    "garch_option_price",
    "GarchParams",
    "vanna",
    "vomma",
    "volga",
    "charm",
    "veta",
    "speed",
    "zomma",
    "color",
    "ultima",
    "dual_delta",
    "dual_gamma",
    "price_array",
    "delta_array",
    "gamma_array",
    "vega_array",
    "greeks_array",
    "HAS_NUMPY",
    "ScenarioGrid",
    "stress_grid",
    "spot_ladder",
    "bjerksund_stensland",
    "bjerksund_stensland_greeks",
    "bjerksund_stensland_1993",
    "bjerksund_stensland_boundary",
    "early_exercise_premium",
    "kim_american_put",
    "kim_american_call",
    "kim_exercise_boundary",
    "kim_put_greeks",
    "baw_american",
    "baw_critical_spot",
    "baw_american_greeks",
    "andreasen_huge_prices",
    "andreasen_huge_smile",
    "andreasen_huge_calibrate",
    "andreasen_huge_strike_greeks",
    "cheyette_G",
    "cheyette_y",
    "cheyette_zero_bond",
    "cheyette_bond_option",
    "cheyette_bond_option_greeks",
    "cheyette_floorlet",
    "cheyette_cap",
    "cheyette_floor",
    "cheyette_caplet",
    "g2pp_V",
    "g2pp_zero_bond",
    "g2pp_bond_option",
    "g2pp_bond_option_greeks",
    "g2pp_caplet",
    "g2pp_floorlet",
    "g2pp_cap",
    "g2pp_floor",
    "bermudan_swaption_g2pp",
    "bermudan_swaption_g2pp_greeks",
    "DiscountCurve",
    "bootstrap_from_swaps",
    "dual_forward_rate",
    "dual_par_swap_rate",
    "dual_swap_value",
    "dual_float_leg_value",
    "dual_calibrate_basis",
    "dual_swap_dv01",
    "__version__",
]
