"""Spherical Bessel functions and modified Bessel functions of integer order.

Extends :mod:`quantforge.bessel` (cylindrical J/Y) and the ``I0``/``I1`` in
:mod:`quantforge.von_mises`. The spherical Bessel functions ``j_n``/``y_n`` are the radial
solutions of the Helmholtz equation in spherical coordinates (partial-wave scattering, the
particle in a sphere); the modified Bessel functions ``I_n``/``K_n`` solve the modified
equation and govern heat flow in a cylinder, skin effect, and the von Mises / Kaiser windows.

``y_n`` is generated by stable upward recurrence, ``j_n`` by downward (Miller) recurrence,
``I_n`` by downward recurrence normalized against ``I0``, and ``K_n`` by upward recurrence from
``K0``/``K1``. Pure standard library.
"""

import math

from .von_mises import bessel_i0, bessel_i1


def spherical_bessel_j(n, x):
    """Spherical Bessel function of the first kind ``j_n(x)``.

    ``j_0 = sin(x)/x``, ``j_1 = sin(x)/x^2 - cos(x)/x``, and
    ``j_{k+1} = (2k+1)/x * j_k - j_{k-1}``. Uses that upward recurrence when ``n <= x`` (stable
    there) and downward Miller recurrence otherwise. ``j_n(0) = 1`` if ``n == 0`` else ``0``.
    """
    if n < 0:
        raise ValueError("spherical_bessel_j requires n >= 0")
    if x == 0.0:
        return 1.0 if n == 0 else 0.0
    j0 = math.sin(x) / x
    if n == 0:
        return j0
    j1 = math.sin(x) / (x * x) - math.cos(x) / x
    if n == 1:
        return j1
    if n <= x:
        jm, jc = j0, j1
        for k in range(1, n):
            jm, jc = jc, (2 * k + 1) / x * jc - jm
        return jc
    # downward Miller recurrence for n > x
    start = n + int(math.sqrt(40.0 * n)) + 15
    jp, jc = 0.0, 1e-30
    target = 0.0
    for k in range(start, 0, -1):
        jm = (2 * k + 1) / x * jc - jp
        jp = jc
        jc = jm
        if k - 1 == n:
            target = jc      # jc == jm == j_{k-1} == j_n
    # normalize against known j_0 (jc holds the scaled j_0 after the loop)
    return target * (j0 / jc)


def spherical_bessel_y(n, x):
    """Spherical Bessel function of the second kind ``y_n(x)`` (a.k.a. spherical Neumann).

    ``y_0 = -cos(x)/x``, ``y_1 = -cos(x)/x^2 - sin(x)/x``, then stable upward recurrence
    ``y_{k+1} = (2k+1)/x * y_k - y_{k-1}``. Singular at ``x = 0``.
    """
    if n < 0:
        raise ValueError("spherical_bessel_y requires n >= 0")
    if x == 0.0:
        raise ValueError("spherical_bessel_y is singular at x = 0")
    y0 = -math.cos(x) / x
    if n == 0:
        return y0
    y1 = -math.cos(x) / (x * x) - math.sin(x) / x
    if n == 1:
        return y1
    ym, yc = y0, y1
    for k in range(1, n):
        ym, yc = yc, (2 * k + 1) / x * yc - ym
    return yc


def bessel_in(n, x):
    """Modified Bessel function of the first kind ``I_n(x)`` for integer ``n >= 0``.

    ``n = 0, 1`` use the A&S approximations in :mod:`quantforge.von_mises`; higher orders use
    downward recurrence ``I_{k-1} = I_{k+1} + (2k/x) I_k`` normalized against ``I0``.
    ``I_n(x) = I_n(-x)`` for even ``n`` and ``-`` for odd; ``I_n(0) = [n == 0]``.
    """
    if n < 0:
        raise ValueError("bessel_in requires n >= 0")
    if n == 0:
        return bessel_i0(x)
    if n == 1:
        return bessel_i1(x)
    if x == 0.0:
        return 0.0
    ax = abs(x)
    # downward recurrence (Miller)
    start = n + int(math.sqrt(40.0 * n)) + 15
    bip, bi = 0.0, 1e-30
    result = 0.0
    for k in range(start, 0, -1):
        bim = bip + (2.0 * k / ax) * bi
        bip = bi
        bi = bim
        if k - 1 == n:
            result = bi      # bi == I_{k-1} == I_n
        # rescale to avoid overflow
        if abs(bi) > 1e30:
            bi *= 1e-30
            bip *= 1e-30
            result *= 1e-30
    result *= bessel_i0(ax) / bi
    if x < 0.0 and n % 2 == 1:
        return -result
    return result


def bessel_kn(n, x):
    """Modified Bessel function of the second kind ``K_n(x)`` for integer ``n >= 0``, ``x > 0``.

    ``K0``/``K1`` use the A&S polynomial approximations; higher orders use the stable upward
    recurrence ``K_{k+1} = K_{k-1} + (2k/x) K_k``. Singular as ``x -> 0``.
    """
    if n < 0:
        raise ValueError("bessel_kn requires n >= 0")
    if x <= 0.0:
        raise ValueError("bessel_kn requires x > 0")
    k0 = _bessel_k0(x)
    if n == 0:
        return k0
    k1 = _bessel_k1(x)
    if n == 1:
        return k1
    km, kc = k0, k1
    for k in range(1, n):
        km, kc = kc, km + (2.0 * k / x) * kc
    return kc


def _bessel_k0(x):
    # Abramowitz & Stegun 9.8.5 / 9.8.6
    if x <= 2.0:
        t = x * x / 4.0
        return (-math.log(x / 2.0) * bessel_i0(x)
                + (-0.57721566 + t * (0.42278420 + t * (0.23069756 + t * (
                    0.03488590 + t * (0.00262698 + t * (0.00010750 + t * 0.00000740)))))))
    t = 2.0 / x
    return (math.exp(-x) / math.sqrt(x)) * (1.25331414 + t * (-0.07832358 + t * (
        0.02189568 + t * (-0.01062446 + t * (0.00587872 + t * (-0.00251540 + t * 0.00053208))))))


def _bessel_k1(x):
    # Abramowitz & Stegun 9.8.7 / 9.8.8
    if x <= 2.0:
        t = x * x / 4.0
        return (math.log(x / 2.0) * bessel_i1(x)
                + (1.0 / x) * (1.0 + t * (0.15443144 + t * (-0.67278579 + t * (
                    -0.18156897 + t * (-0.01919402 + t * (-0.00110404 + t * -0.00004686)))))))
    t = 2.0 / x
    return (math.exp(-x) / math.sqrt(x)) * (1.25331414 + t * (0.23498619 + t * (
        -0.03655620 + t * (0.01504268 + t * (-0.00780353 + t * (0.00325614 + t * -0.00068245))))))
