"""Combinatorial ranking: Gray code, permutation and combination rank/unrank.

Bijections between integers and combinatorial objects -- so a permutation or a subset can
be stored as a single index, generated by index, or iterated without materializing all of
them. Provides the reflected binary Gray code, permutation rank/unrank via the Lehmer
code (factorial number system), and combination rank/unrank via the combinatorial number
system. All round-trip exactly. Pure standard library.
"""

from math import comb, factorial


def gray_code(n):
    """Reflected binary Gray code of a non-negative integer ``n`` (``n XOR (n >> 1)``).

    Consecutive Gray codes differ in exactly one bit. The inverse is
    :func:`gray_decode`.
    """
    if n < 0:
        raise ValueError("n must be non-negative")
    return n ^ (n >> 1)


def gray_decode(g):
    """Inverse of :func:`gray_code`: recover the integer from its Gray code."""
    if g < 0:
        raise ValueError("g must be non-negative")
    n = 0
    while g:
        n ^= g
        g >>= 1
    return n


def permutation_unrank(rank, n):
    """The ``rank``-th permutation of ``[0, n)`` in lexicographic order (Lehmer code).

    ``rank`` in ``[0, n!)``. Returns a list. ``permutation_unrank(0, n)`` is the identity.
    """
    if n < 0:
        raise ValueError("n must be >= 0")
    if not (0 <= rank < max(1, factorial(n))):
        raise ValueError("rank out of range [0, n!)")
    available = list(range(n))
    perm = []
    r = rank
    for i in range(n, 0, -1):
        f = factorial(i - 1)
        idx = r // f
        r -= idx * f
        perm.append(available.pop(idx))
    return perm


def permutation_rank(perm):
    """Lexicographic rank of a permutation of ``[0, n)`` (inverse of :func:`permutation_unrank`).

    ``perm`` must be a permutation of ``0..n-1``. Returns an integer in ``[0, n!)``.
    """
    n = len(perm)
    if sorted(perm) != list(range(n)):
        raise ValueError("perm must be a permutation of 0..n-1")
    available = list(range(n))
    rank = 0
    for i, v in enumerate(perm):
        idx = available.index(v)
        rank += idx * factorial(n - 1 - i)
        available.pop(idx)
    return rank


def combination_unrank(rank, n, k):
    """The ``rank``-th ``k``-subset of ``[0, n)`` in lexicographic order.

    Uses the combinatorial number system. ``rank`` in ``[0, C(n, k))``. Returns a sorted
    list of ``k`` indices.
    """
    if not (0 <= k <= n):
        raise ValueError("require 0 <= k <= n")
    total = comb(n, k)
    if not (0 <= rank < max(1, total)):
        raise ValueError("rank out of range [0, C(n, k))")
    result = []
    r = rank
    start = 0
    for i in range(k):
        # Choose the next element; count subsets skipping it until r fits.
        remaining = k - i
        c = start
        while True:
            count = comb(n - c - 1, remaining - 1)
            if r < count:
                break
            r -= count
            c += 1
        result.append(c)
        start = c + 1
    return result


def combination_rank(combo, n):
    """Lexicographic rank of a ``k``-subset of ``[0, n)`` (inverse of :func:`combination_unrank`).

    ``combo`` is a sorted (or sortable) iterable of distinct indices in ``[0, n)``. Returns
    an integer in ``[0, C(n, k))``.
    """
    c = sorted(combo)
    k = len(c)
    if len(set(c)) != k or (c and (c[0] < 0 or c[-1] >= n)):
        raise ValueError("combo must be distinct indices in [0, n)")
    rank = 0
    prev = -1
    for i, v in enumerate(c):
        remaining = k - i
        for x in range(prev + 1, v):
            rank += comb(n - x - 1, remaining - 1)
        prev = v
    return rank
