"""De Bruijn sequences and Lyndon words.

A de Bruijn sequence ``B(k, n)`` is a cyclic string over a size-``k`` alphabet in which every
length-``n`` string appears exactly once as a (cyclic) substring -- length ``k^n``. It is
built here by concatenating, in lexicographic order, the *Lyndon words* whose length divides
``n`` (the Fredricksen-Kessler-Maiorana algorithm, generated by Duval's ``O(k^n)``
constant-amortized-time method). Lyndon words -- strings strictly smaller than all their
rotations -- are exposed directly too. Pure standard library.
"""


def lyndon_words(alphabet_size, max_len):
    """Generate all Lyndon words over ``{0..alphabet_size-1}`` of length ``<= max_len``.

    Returns a list of tuples in lexicographic order (Duval's algorithm). A Lyndon word is a
    nonempty string strictly smaller than all its proper rotations.
    """
    if alphabet_size < 1:
        raise ValueError("alphabet_size must be >= 1")
    if max_len < 0:
        raise ValueError("max_len must be non-negative")
    k = alphabet_size
    result = []
    w = [-1]
    while w:
        w[-1] += 1
        m = len(w)
        if m <= max_len:
            result.append(tuple(w))
        # extend to length max_len by repeating the current necklace prefix
        while len(w) < max_len:
            w.append(w[len(w) - m])
        # strip trailing symbols equal to k-1 to get the next candidate
        while w and w[-1] == k - 1:
            w.pop()
    return result


def is_lyndon(word):
    """True if ``word`` (a sequence) is a Lyndon word: strictly smaller than all rotations."""
    w = list(word)
    n = len(w)
    if n == 0:
        return False
    return all(w < w[i:] + w[:i] for i in range(1, n))


def de_bruijn_sequence(alphabet_size, n):
    """Return a de Bruijn sequence ``B(k, n)`` as a list of symbols (length ``k^n``).

    Every length-``n`` string over ``{0..k-1}`` occurs exactly once as a cyclic substring.
    Built by the FKM algorithm: concatenate the Lyndon words whose length divides ``n``, in
    lexicographic order.
    """
    if alphabet_size < 1:
        raise ValueError("alphabet_size must be >= 1")
    if n < 1:
        raise ValueError("n must be >= 1")
    k = alphabet_size
    sequence = []
    w = [-1]
    while w:
        w[-1] += 1
        m = len(w)
        if n % m == 0:
            sequence.extend(w)
        while len(w) < n:
            w.append(w[len(w) - m])
        while w and w[-1] == k - 1:
            w.pop()
    return sequence
