"""Gauss-Hermite quadrature for Gaussian-weighted expectations.

Many finance integrals are expectations under a normal density: option values,
mixing over a latent factor, moment calculations. Gauss-Hermite quadrature
approximates

    E[g(Z)] = integral g(z) phi(z) dz ~ sum_i w_i g(x_i),   Z ~ N(0, 1),

with ``n`` nodes exact for polynomials up to degree ``2n - 1``. The nodes and
weights use the probabilists' convention (weight ``phi(z)``, the standard normal
density) and are generated by the Golub-Welsch algorithm: the nodes are the
eigenvalues of the symmetric tridiagonal Jacobi matrix of the Hermite three-term
recurrence (zero diagonal, off-diagonal ``sqrt(k)``), and the weights are the
squared first components of the normalized eigenvectors. Pure standard library on
top of :mod:`quantforge.pca`.
"""

import math

from .pca import jacobi_eigen


def gauss_hermite_nodes_weights(n):
    """Probabilists' Gauss-Hermite nodes and weights for ``n`` points.

    Returns ``(nodes, weights)`` for the weight function ``phi(z)`` (standard
    normal density), so ``sum_i w_i = 1`` and ``sum_i w_i x_i^{2m}`` reproduces the
    standard-normal moments. Exact for polynomials up to degree ``2n - 1``. Nodes
    are symmetric about zero and returned in increasing order.
    """
    if n < 1:
        raise ValueError("n must be at least 1")
    if n == 1:
        return [0.0], [1.0]
    # Symmetric tridiagonal Jacobi matrix of the probabilists' Hermite recurrence:
    # zero diagonal, off-diagonal beta_k = sqrt(k).
    jac = [[0.0] * n for _ in range(n)]
    for k in range(1, n):
        b = math.sqrt(k)
        jac[k][k - 1] = b
        jac[k - 1][k] = b
    eigenvalues, eigenvectors = jacobi_eigen(jac)
    # Golub-Welsch weight = mu_0 * (first component of the unit eigenvector)^2,
    # with mu_0 = integral phi = 1. eigenvectors[i] pairs with eigenvalues[i].
    pairs = []
    for i in range(n):
        vec = eigenvectors[i]
        norm = math.sqrt(sum(c * c for c in vec))
        first = vec[0] / norm
        pairs.append((eigenvalues[i], first * first))
    pairs.sort(key=lambda p: p[0])
    nodes = [p[0] for p in pairs]
    weights = [p[1] for p in pairs]
    # The distribution is exactly symmetric about zero; fold mirror pairs together
    # to remove the eigensolver's asymmetric floating error (which, magnified by a
    # large node raised to an odd power, would otherwise leak into odd moments).
    for i in range(n // 2):
        j = n - 1 - i
        x_sym = 0.5 * (nodes[j] - nodes[i])   # positive magnitude
        nodes[i], nodes[j] = -x_sym, x_sym
        w_sym = 0.5 * (weights[i] + weights[j])
        weights[i] = weights[j] = w_sym
    if n % 2:
        nodes[n // 2] = 0.0
    # Renormalize so the weights sum to exactly one (mu_0 = 1).
    total = sum(weights)
    weights = [w / total for w in weights]
    return nodes, weights


def gauss_hermite_expectation(g, mu=0.0, sigma=1.0, n=16):
    """Approximate ``E[g(X)]`` for ``X ~ N(mu, sigma^2)`` by Gauss-Hermite quadrature.

    Shifts and scales the standard-normal nodes to ``x_i = mu + sigma * z_i`` and
    forms ``sum_i w_i g(x_i)``. Exact when ``g`` is a polynomial of degree at most
    ``2n - 1``. With ``sigma = 0`` it collapses to ``g(mu)``.
    """
    if sigma < 0.0:
        raise ValueError("sigma must be non-negative")
    if sigma == 0.0:
        return g(mu)
    nodes, weights = gauss_hermite_nodes_weights(n)
    return sum(weights[i] * g(mu + sigma * nodes[i]) for i in range(len(nodes)))
