"""Unified implied-vol surface builder for the exponential-Levy models.

Any Levy model on the shared Carr-Madan engine (VG, NIG, Meixner, CGMY) has a
single set of parameters that already fixes the *whole* surface -- unlike SVI,
which fits one slice per expiry. This module turns a ``(model, params)`` pair
into an implied-vol surface across a grid of expiries and log-moneyness, pricing
each expiry with one Carr-Madan FFT strip (so the cost is one transform per
maturity), and checks it for calendar arbitrage the same way
:class:`quantforge.VolSurface` does: total implied variance ``w = sigma^2 t``
must be non-decreasing in maturity at every fixed log-moneyness.
"""

import math
from dataclasses import dataclass
from typing import Dict, List, Sequence, Tuple

from .levycalib import levy_psi, _strip_vols


@dataclass(frozen=True)
class LevyCalendarViolation:
    t_short: float
    t_long: float
    k: float
    w_short: float
    w_long: float           # < w_short => calendar arbitrage


class LevySurface:
    """Implied-vol surface generated by one exponential-Levy parameter set."""

    def __init__(self, model, params, S, r, q=0.0, cm_alpha=1.5):
        self.model = model
        self.params = tuple(params)
        self.S = S
        self.r = r
        self.q = q
        self.cm_alpha = cm_alpha
        self._psi = levy_psi(model, params)

    def implied_vol(self, k, t):
        """Black-Scholes implied vol at forward log-moneyness ``k`` and expiry ``t``.

        ``k = ln(K / F_t)`` on the forward ``F_t = S e^{(r-q) t}``.
        """
        F = self.S * math.exp((self.r - self.q) * t)
        K = F * math.exp(k)
        iv = _strip_vols(self.S, t, self.r, self.q, self._psi, [K],
                         self.cm_alpha)[0]
        return iv

    def total_variance(self, k, t):
        """Total implied variance ``w(k, t) = sigma^2 t``."""
        iv = self.implied_vol(k, t)
        return iv * iv * t

    def grid(self, expiries: Sequence[float], ks: Sequence[float]):
        """Return ``{t: [(k, iv), ...]}`` over the expiry x log-moneyness grid.

        Each expiry is priced with a single Carr-Madan FFT strip, so building an
        ``E x K`` surface costs ``E`` transforms rather than ``E*K`` integrals.
        """
        out = {}
        for t in expiries:
            F = self.S * math.exp((self.r - self.q) * t)
            strikes = [F * math.exp(k) for k in ks]
            ivs = _strip_vols(self.S, t, self.r, self.q, self._psi, strikes,
                              self.cm_alpha)
            out[float(t)] = [(k, iv) for k, iv in zip(ks, ivs)
                             if iv == iv]  # drop NaNs
        return out

    def calendar_violations(self, expiries: Sequence[float],
                            ks: Sequence[float] = None, tol=1e-9):
        """List calendar-arbitrage violations across the given expiries.

        For each adjacent expiry pair and each ``k`` the total variance must not
        fall as maturity grows; any drop beyond ``tol`` is reported.
        """
        if ks is None:
            ks = [x * 0.05 for x in range(-8, 9)]  # k in [-0.4, 0.4]
        ts = sorted(expiries)
        viol = []
        # Precompute w over the grid once.
        wgrid = {t: {k: self.total_variance(k, t) for k in ks} for t in ts}
        for t_lo, t_hi in zip(ts, ts[1:]):
            for k in ks:
                w_lo = wgrid[t_lo][k]
                w_hi = wgrid[t_hi][k]
                if w_hi < w_lo - tol:
                    viol.append(LevyCalendarViolation(t_lo, t_hi, k, w_lo, w_hi))
        return viol

    def is_calendar_arbitrage_free(self, expiries, ks=None, tol=1e-9):
        return not self.calendar_violations(expiries, ks, tol)
