"""Stern-Brocot tree and Farey sequences: the structure of the rationals.

Every positive rational appears exactly once in the Stern-Brocot tree, reached by a unique
path of left/right mediant steps from ``1/1``. Walking toward a target rational gives its
path (a run-length-encoded continued fraction) and, truncated, its best rational
approximations with bounded denominator. The Farey sequence of order ``n`` lists every
reduced fraction in ``[0, 1]`` with denominator ``<= n`` in increasing order, generated by
the mediant recurrence. Exact integer arithmetic throughout. Pure standard library.
"""

from fractions import Fraction
from math import gcd


def mediant(a, b):
    """Mediant of two fractions ``a = p/q`` and ``b = r/s``: ``(p + r)/(q + s)``.

    ``a`` and ``b`` may be `Fraction` or ``(num, den)`` pairs. The mediant lies strictly
    between them and is the fraction the Stern-Brocot / Farey construction inserts.
    """
    pa, qa = (a.numerator, a.denominator) if isinstance(a, Fraction) else a
    pb, qb = (b.numerator, b.denominator) if isinstance(b, Fraction) else b
    return Fraction(pa + pb, qa + qb)


def stern_brocot_path(target, max_steps=10000):
    """Return the L/R path from ``1/1`` to a positive rational ``target`` in the tree.

    ``target`` is a `Fraction` (or something `Fraction` accepts). Returns a string of ``'L'``
    and ``'R'`` steps; the empty string means ``target == 1``. Raises for non-positive
    targets or if ``max_steps`` is exceeded (non-terminating only for irrationals).
    """
    t = Fraction(target)
    if t <= 0:
        raise ValueError("target must be a positive rational")
    lo = (0, 1)      # left boundary 0/1
    hi = (1, 0)      # right boundary 1/0 (infinity)
    path = []
    for _ in range(max_steps):
        med = mediant(lo, hi)
        if med == t:
            return "".join(path)
        if t < med:
            hi = (med.numerator, med.denominator)
            path.append("L")
        else:
            lo = (med.numerator, med.denominator)
            path.append("R")
    raise ValueError("target not reached within max_steps (is it rational?)")


def stern_brocot_from_path(path):
    """Return the fraction at a given L/R ``path`` from ``1/1``."""
    lo = (0, 1)
    hi = (1, 0)
    med = mediant(lo, hi)
    for step in path:
        if step == "L":
            hi = (med.numerator, med.denominator)
        elif step == "R":
            lo = (med.numerator, med.denominator)
        else:
            raise ValueError("path must contain only 'L' and 'R'")
        med = mediant(lo, hi)
    return med


def best_rational_bounded(x, max_denominator):
    """Closest fraction to ``x`` with denominator ``<= max_denominator`` (Stern-Brocot descent).

    Walks the tree toward ``x``, stopping when the next mediant would exceed the denominator
    bound, and returns the nearer of the two current boundaries. ``x`` may be any real.
    """
    if max_denominator < 1:
        raise ValueError("max_denominator must be >= 1")
    lo = Fraction(0, 1)
    hi = None                       # +infinity boundary
    # bracket x between consecutive integers first
    n = int(x)
    lo = Fraction(n, 1)
    hi = Fraction(n + 1, 1)
    if x == lo:
        return lo
    best = lo if abs(float(lo) - x) <= abs(float(hi) - x) else hi
    for _ in range(10 * max_denominator + 10):
        med = mediant(lo, hi)
        if med.denominator > max_denominator:
            break
        if abs(float(med) - x) < abs(float(best) - x):
            best = med
        if x < med:
            hi = med
        elif x > med:
            lo = med
        else:
            return med
    return best


def farey_sequence(n):
    """Return the Farey sequence of order ``n``: reduced fractions in ``[0, 1]``, ascending.

    Uses the ``O(1)``-per-term neighbour recurrence, so no gcd or sorting is needed.
    """
    if n < 1:
        raise ValueError("n must be >= 1")
    result = [Fraction(0, 1)]
    # neighbour recurrence: (a/b, c/d) start at (0/1, 1/n) and march to (1/1, ...)
    a, b, c, d = 0, 1, 1, n
    result.append(Fraction(c, d))
    while not (c == 1 and d == 1):
        k = (n + b) // d
        a, b, c, d = c, d, k * c - a, k * d - b
        result.append(Fraction(c, d))
    return result
